image:
  - Ubuntu
  - macOS
  - Visual Studio 2019

environment:
  TINYTEX_INSTALLER: TinyTeX

build: off

for:
-
  matrix:
    only:
      - image: Ubuntu
  branches:
    only:
      - master
  skip_tags: true

  install:
    - "[ ! -z ${GH_KEY} ] || exit 0"
    - |
      eval "$(ssh-agent -s)"
      echo ${GH_KEY} | base64 -d > ~/id_rsa
      chmod 0600 ~/id_rsa
      ssh-add ~/id_rsa
      git config user.email "xie@yihui.name"
      git config user.name "Yihui Xie"
    - export CURRENT_TAG=$(date "+%Y.%m")$TINYTEX_PATCH_VERSION
    # if the tag must exist, download and exit (deploy the daily build)
    - |
      if [ $(git tag -l "v${CURRENT_TAG}") ]; then
        CURRENT_TAG=""
      fi
    - ./download.sh
    - ./install-gh.sh
    - |
      if [ -z $CURRENT_TAG ]; then
        export TINYTEX_RELEASE=daily
      else
        export TINYTEX_RELEASE=v${CURRENT_TAG}
        sed -i -E "s|(\s*<version>)([0-9.]+)(</version>\s*)|\1${CURRENT_TAG}\3|" choco/tinytex.nuspec
        sed -i -E "s|(\s*checksum\s*=\s*')([0-9a-f]{32})('\\s*)|\1$(md5sum TinyTeX-1-v${CURRENT_TAG}.zip | cut -d' ' -f1)\3|" choco/tools/chocolateyinstall.ps1
        git add -u
        git diff-index --quiet HEAD && exit 0 || git commit -m"TinyTeX release v${CURRENT_TAG}"
      fi
      git tag -f $TINYTEX_RELEASE
      git push -f --tags git@github.com:${APPVEYOR_REPO_NAME}.git $APPVEYOR_REPO_BRANCH
    - |
      if [ $TINYTEX_RELEASE != 'daily' ]; then
        gh release create $TINYTEX_RELEASE -F notes.md -t "TinyTeX $TINYTEX_RELEASE"
        gh release upload $TINYTEX_RELEASE TinyTeX* tinitex.* installer-unix*.tar.gz --clobber
      else
        gh release upload $TINYTEX_RELEASE TinyTeX* --clobber
      fi

-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - cd choco
    - choco pack
    - choco install --no-progress tinytex -source "'.;https://chocolatey.org/api/v2/'"
    - choco uninstall -y tinytex
    - ps: |
        if ( ($Env:APPVEYOR_REPO_TAG -eq "true") -and ($Env:APPVEYOR_REPO_TAG_NAME -ne "daily") ) {
          choco apikey --key $Env:CHOCO_KEY --source https://push.chocolatey.org/
          choco push --source https://push.chocolatey.org/
        }
    - cd ..
    - ps: |
        if ($Env:APPVEYOR_REPO_TAG -eq "true") {
          Exit-AppVeyorBuild
        }
    - ps: |
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-WebRequest https://yihui.org/tinytex/install-bin-windows.bat -OutFile install-bin-windows.bat
    - install-bin-windows.bat
    - call "%APPDATA%\\TinyTeX\\bin\\win32\\tlmgr" update --self
    - call "%APPDATA%\\TinyTeX\\bin\\win32\\tlmgr" install scheme-full
    - ps: Compress-Archive $Env:APPDATA\\TinyTeX TinyTeX-2.zip
    - choco install gh
    - refreshenv
    - gh release upload daily TinyTeX-2.zip --clobber -R %APPVEYOR_REPO_NAME%

-
  matrix:
    only:
      - image: macOS
  skip_tags: true

  install:
    - "curl -sL https://yihui.org/tinytex/install-bin-unix.sh | sh"
    - tlmgr install scheme-full || true
    - tar zcf TinyTeX-2.tgz -C ~/Library TinyTeX
    - brew install gh
    - gh release upload daily TinyTeX-2.tgz --clobber
